### ISSUE TITLE
Compiled for too old Android version

### ISSUE THREAD

**Issue by Piotr-Wieczorek** [Farmer-Markus/s25rttr-android#1]
This app is unsupported on Android 14 which only allows for running Android 6 and later apps.
![Screenshot_20240919-092546_Sklep Google Play](https://github.com/user-attachments/assets/f3d790bc-a7cf-496b-9b95-eebcd009a2bc)

**Comment by Farmer-Markus** [comment]
But you should be able to install it anyway by clicking on "more details". There should be a button to install it. I need to compile such an old android version due to the storage permission. The new android storage system is horrible to port apps.
